[versions]
kotlin = "1.6.21"
android-plugin = "7.1.3"
gradleWrapper = "7.4.2"
junit5 = "5.5.2"
commonsIo = "2.8.0"
archUnit = "0.16.0"
asm = "7.0"
jdom2 = "2.0.5"
gradle-test-toolkit = "1.0.3"
gson = "2.8.9"
sample-plugin = "1.0.0-SNAPSHOT"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-script-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
android-material = { module = "com.google.android.material:material", version = "1.3.0" }
androidx-ktx = { module = "androidx.core:core-ktx", version = "1.3.2" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.1.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.2.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.0.4" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.1.0" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.0.0" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
junit = { module = "junit:junit", version = "4.13.2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
gradle-test-toolkit = { module = "io.github.jackchen365:gradle-test-toolkit", version.ref = "gradle-test-toolkit" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
java-asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
java-asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
jdom2 = { module = "org.jdom:jdom2", version.ref = "jdom2" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
recyclerview-library = { module = "com.github.momodae.RecyclerViewLibrary2:adapter", version = "1.0.1" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.21.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.3.0" }
sample = { id = "com.airsaid.sample", version.ref = "sample-plugin" }